# Generated by Django 5.0.2 on 2024-02-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0004_alter_invoice_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.CharField(max_length=10),
        ),
    ]
