# Generated by Django 5.0.2 on 2024-02-28 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0005_alter_invoice_due_date_alter_invoice_invoice_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invoice',
            table='mini_invoices',
        ),
    ]
