# Generated by Django 5.0.2 on 2024-02-29 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0006_alter_invoice_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invoice',
            table='invoices',
        ),
    ]
