# Generated by Django 5.0.2 on 2024-02-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0007_alter_invoice_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.IntegerField(unique=True),
        ),
    ]
