# Generated by Django 5.0.2 on 2024-02-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0008_invoice_id_alter_invoice_invoice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='id',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
