# Generated by Django 5.0.2 on 2024-02-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0009_remove_invoice_id_alter_invoice_invoice_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('login_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
