# Generated by Django 5.0.2 on 2024-02-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0010_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_id',
            field=models.EmailField(max_length=50),
        ),
    ]
