# Generated by Django 5.0.2 on 2024-02-29 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0012_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='item_price',
        ),
    ]
