# Generated by Django 5.0.2 on 2024-02-29 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0016_alter_products_invoice_id_alter_products_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.IntegerField()),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini.invoice')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
