# Generated by Django 5.0.2 on 2024-02-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0017_product_delete_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_name',
            field=models.CharField(max_length=20),
        ),
    ]
