# Generated by Django 5.0.2 on 2024-02-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0018_alter_product_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='invoice_id',
            field=models.IntegerField(),
        ),
    ]
