# Generated by Django 5.0.2 on 2024-02-29 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0019_alter_product_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='invoice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini.invoice'),
        ),
    ]
