# Generated by Django 5.0.2 on 2024-03-01 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0020_alter_product_invoice_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Item',
        ),
        migrations.AlterModelTable(
            name='item',
            table='items',
        ),
    ]
