# Generated by Django 5.0.2 on 2024-03-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0021_rename_product_item_alter_item_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
