# Generated by Django 5.0.2 on 2024-03-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0022_alter_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='invoice_id',
            field=models.IntegerField(),
        ),
    ]
