# Generated by Django 5.0.2 on 2024-03-01 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0023_alter_item_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='invoice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini.invoice'),
        ),
    ]
