# Generated by Django 5.0.2 on 2024-03-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0026_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ph',
            field=models.IntegerField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='login_id',
            field=models.IntegerField(max_length=10),
        ),
    ]
