# Generated by Django 5.0.2 on 2024-03-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0027_customer_ph_alter_customer_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(max_length=75),
        ),
    ]
