# Generated by Django 5.0.2 on 2024-03-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0028_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_amt',
            field=models.CharField(max_length=40),
        ),
    ]
