# Generated by Django 5.0.2 on 2024-03-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0029_alter_invoice_total_amt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_id', models.IntegerField()),
                ('bank_name', models.CharField(max_length=20)),
                ('account_no', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
