# Generated by Django 5.0.2 on 2024-03-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0031_rename_ifsc_payments_isfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='account_no',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='bank_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='isfc',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='pay_id',
            field=models.IntegerField(null=True),
        ),
    ]
